sonar.projectKey=aveave_sonar-cloud-research
sonar.organization=sonarcloudresearch
sonar.host.url=https://sonarcloud.io

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.junit.reportPaths=target/surefire-reports

# Full analysis exclusions (files are ignored by Sonar analyzers)
sonar.exclusions=src/main/java/com/example/demo/model/**

# Coverage-only exclusion (file is analyzed but excluded from coverage)
sonar.coverage.exclusions=src/main/java/com/example/demo/DemoApplication.java
