spring.application.name=sonar-cloud-research

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mydatabase}
spring.datasource.username=${DB_USERNAME:myuser}
spring.datasource.password=${DB_PASSWORD:mypassword}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

app.kafka.employee-created-topic=${EMPLOYEE_CREATED_TOPIC:employee-created}
compensation.taxes.number=${COMPENSATION_TAXES_NUMBER:15}
